
/*SETOR*/
SELECT
DISTINCT X.CD_SETOR_ATENDIMENTO2,
X.DS_SETOR_ATENDIMENTO,
X.IE_EVOLUCAO_CLINICA,
X.NR_ATENDIMENTO

FROM
(


/*AMBOS*/
SELECT
    B.CD_SETOR_ATENDIMENTO CD_SETOR_ATENDIMENTO2,
    B.DS_SETOR_ATENDIMENTO,
    A.IE_EVOLUCAO_CLINICA,
    B.NR_ATENDIMENTO
FROM
    ATENDIMENTO_PACIENTE_V B,
    EVOLUCAO_PACIENTE A
WHERE
    A.DT_EVOLUCAO BETWEEN TO_DATE('24/08/2023 00:00:00','DD/MM/YYYY HH24:MI:SS') 
    AND FIM_DIA(TO_DATE('25/08/2024 07:45:00','DD/MM/YYYY HH24:MI:SS'))
    AND A.NR_ATENDIMENTO = B.NR_ATENDIMENTO
    --AND (( B.CD_SETOR_ATENDIMENTO =:CD_SETOR_ATENDIMENTO )OR ( 0 =:CD_SETOR_ATENDIMENTO ))
    --AND A.DT_LIBERACAO IS NOT NULL
    AND A.IE_SITUACAO = 'A'
    --AND :IE_ALTA = 'A'
)X
WHERE
--IE_EVOLUCAO_CLINICA in ('EVP')
NR_ATENDIMENTO = 1933841 
ORDER BY 2

--IE_EVOLUCAO_CLINICA in ('E') = EVOLUÇÃO MÉDICA