--CATE 1801
NUM PEÇAS FALTANTES
NOME PEÇA FALTANTE
núm. total de peças - núm. peças limpas  =  Peças faltantes 
-------------------------------------
SELECT
'Conjunto: '||SUBSTR(DECODE(A.NM_CONJUNTO_AUX,NULL,CME_OBTER_NOME_CONJUNTO(A.NR_SEQ_CONJUNTO),
A.NM_CONJUNTO_AUX),1,200) DS_CONJUNTO,
A.NR_SEQUENCIA nr_seq_lote_barras,
'Data Preparo: '||TO_CHAR(A.DT_ORIGEM,'DD/MM/YYYY HH24:MI:SS') DT_ORIGEM,
'Embalagem: '||SUBSTR(DECODE(A.DS_EMBALAGEM_AUX,NULL,CME_OBTER_CLASSIF_EMBALAGEM(A.NR_SEQ_EMBALAGEM),A.DS_EMBALAGEM_AUX),1,50) DS_EMBALAGEM,
'N° Pecas: '||(SELECT SUM(QT_ITEM)FROM CM_ITEM_CONT WHERE NR_SEQ_CONJUNTO = A.NR_SEQUENCIA)QT_PECAS,
'Observacao: '||A.DS_OBSERVACAO DS_OBSERVACAO,
'Responsavel: '||SUBSTR(DECODE(A.NM_PESSOA_RESP_AUX,NULL,OBTER_NOME_PF(A.CD_PESSOA_RESP),A.NM_PESSOA_RESP_AUX),1,60) NM_PESSOA
FROM CM_CONJUNTO_CONT A
WHERE A.NR_SEQUENCIA = :NR_SEQUENCIA
AND A.IE_STATUS_CONJUNTO = 1